<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Sree" failures="1" tests="3" name="AutomationExerciseTests" time="54.108" errors="0" timestamp="2025-10-05T19:47:14 IST">
  <testcase classname="com.AutomationExercise.Tests.TC01_RegisterUser" name="registerUserTest" time="10.833"/>
  <testcase classname="com.AutomationExercise.Tests.TC02_LoginUser" name="loginUserTest" time="24.547">
    <failure type="java.lang.AssertionError" message="User is not logged in expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is not logged in expected [true] but found [false]
at com.AutomationExercise.Tests.TC02_LoginUser.loginUserTest(TC02_LoginUser.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginUserTest -->
  <testcase classname="com.AutomationExercise.Tests.TC03_LoginWithIncorrectCredentials" name="shouldDisplayErrorForInvalidLoginCredentials" time="4.401"/>
  <testcase classname="com.AutomationExercise.BaseTest.baseTest" name="@AfterSuite flushReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushReport -->
  <testcase classname="com.AutomationExercise.BaseTest.baseTest" name="@AfterSuite flushReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushReport -->
  <testcase classname="com.AutomationExercise.BaseTest.baseTest" name="@BeforeSuite setupReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupReport -->
  <testcase classname="com.AutomationExercise.BaseTest.baseTest" name="@BeforeSuite setupReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupReport -->
</testsuite> <!-- AutomationExerciseTests -->
